[package]
name = "redis-core"
version = "0.1.0"
authors = ["bso <sergey.boyko0791@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
byteorder = "1.3"
bytes = "0.4.12"
